### ISSUE TITLE
Add end of game overlay-interface

### ISSUE THREAD

**Issue by niklassc7** [sopra-fs21-group-15/client#56]
Part of #13

Similar to the scoreboard-overlay (#54), after the end of the game show a overlay with the end-highscore of each user, this can use the same API-request the scoreboard in #54 uses.

This overlay however, will have two additional buttons "return to lobby", "start new round".
"start a new round" is only visible for the room owner.

**Comment by Kilian-Christen** [comment]
Front End implemented Back end not ready
